### ISSUE TITLE
Have you considered incorporating disko?

### ISSUE THREAD

**Issue by stratosgear** [jakehamilton/config#15]
Have you ever considered to incorporate [disko](https://github.com/nix-community/disko) in your configs?

It really removes a lot of manual steps while installing a new system.  I know that it's not like that you reconfigure your disks everyday (once you get a system up and running) but in my trip learning nixos and learning on how to properly setup a new host, disko gives me the ability to destroy and recreate a test vm without having to go through a lengthy install process.  

I will admit that there will be more value for me in seeing your integration process (for my own educational purposes), than you might find actual value for your repo, but I ask nonetheless... :)

Thanks!

**Comment by jakehamilton** [comment]
I've thought about it! I haven't really needed it just yet so I haven't implemented it. There is also some trouble with creating the configuration the first time since you need to know drive names and layout in order to write the config. So you get into the weird state of having to boot the machine, gather drive info, write disko config, and then format... when I could have just formatted things myself. Though it certainly would help if I intended to reformat the same drives multiple times.
